language: csharp
solution: Singularity/Singularity.sln
before_install:
  - wget http://www.builtwithmonogame.com/releases/v3.4/MonoGame.Linux.zip
  - unzip MonoGame.Linux.zip
  - find * -type f -exec chmod 777 {} \; # lazy just make all executable
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run
  - chmod +x monogame-sdk.run
install:
  - sudo apt-get install -qq monodevelop libopenal-dev referenceassemblies-pcl ttf-mscorefonts-installer gtk-sharp2 gtk-sharp3 mono-devel; # install needed packages for the monogame sdk
  - yes Y | sudo ./monogame-sdk.run; # install monogame sdk
  - sudo ./generate.sh && yes Y|sudo ./monogame-linux.run; # install monogame sdk
  - sudo cp -r /usr/lib/mono/xbuild/MonoGame/v3.0/Assemblies/DesktopGL /usr/lib/mono/xbuild/MonoGame/v3.0/Assemblies/Windows
script:
  - (cd Singularity/Singularity/Content/ && mono /opt/monogame-pipeline/MGCB.exe /rebuild /@:"Content.mgcb" /outputDir:"../bin/Release/Content")
  - sudo mdtool build Singularity/Singularity/Singularity.csproj
  # this is actually necessary since otherwise for some reason there's no acesses to Build-required temp-paths.
